### ISSUE TITLE
GIANT: Error scipy version

### ISSUE THREAD

**Issue by lacardonap** [scottyhq/isce_notes#4]
When I run ProcessStack.py I get an error in the file "/home/geored/Software/earthdef/giant/GIAnT/tsinsar/stack.py", line 274 because the st.nanstd function does not exist. 

I found that the function nanstd was a deprecated function that was removed from scipy.stats in version 0.18.0.  https://stackoverflow.com/questions/40944243/module-scipy-stats-has-no-attribute-nanmean

It is necessary to adjust the isce_notes/Ubuntu/giant_102016.yml to downgrade the version of scipy.

```
ProcessStack.py 
logger - INFO - GIANT Toolbox - v 1.0
logger - INFO - ---------------------
<module> - INFO - Input h5file: Stack/RAW-STACK.h5
<module> - INFO - Deleting previous Stack/PROC-STACK.h5
<module> - INFO - Output h5file: Stack/PROC-STACK.h5
<module> - INFO - Using RAW Igram for GPS deramping
<module> - INFO - Taking GPS velocities from file gps_list
lltoij - INFO - Number of viable GPS: 58
lltoij - INFO - Number of GPS stations in Frame: 58
Stations:  58
<module> - INFO - Correcting RAMP using GPS
deramp_gps - INFO - Estimating ramp coefficients
/home/geored/Software/earthdef/giant/GIAnT/tsinsar/stack.py:264: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  Afull[:,mast*poly:(mast+1)*poly] = A
/home/geored/Software/earthdef/giant/GIAnT/tsinsar/stack.py:265: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  Afull[:,slav*poly:(slav+1)*poly] = -A
Traceback (most recent call last):
  File "/home/geored/Software/earthdef/giant/GIAnT/SCR/ProcessStack.py", line 302, in <module>
    rstack.deramp_gps(drstack,gpssar,network=netramp,neigh=gpspad,minnum=gpsmin)
  File "/home/geored/Software/earthdef/giant/GIAnT/tsinsar/stack.py", line 274, in deramp_gps
    dpherr[ppp] = st.nanstd(data.flatten())
AttributeError: 'module' object has no attribute 'nanstd'
```

**Comment by scottyhq** [comment]
Thanks for pointing this out @lacardonap! I'm not using these tools regularly, so they will at times be out of date. If you have a version of giant.yml that is working feel free to submit a pull request and I will add it to this repository
